# Generated by Django 3.2.16 on 2023-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230508_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tile',
            new_name='title',
        ),
    ]
